apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: {{ .Values.vault.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.auth.tokenSecretRef.name }}
          key: {{ .Values.vault.auth.tokenSecretRef.key }}
          namespace: {{ .Values.vault.auth.tokenSecretRef.namespace }}
