apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.cloudflareToken.externalSecret.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  refreshInterval: {{ .Values.cloudflareToken.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.cloudflareToken.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.cloudflareToken.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.cloudflareToken.externalSecret.target.name }}
    creationPolicy: {{ .Values.cloudflareToken.externalSecret.target.creationPolicy }}
  data:
    - secretKey: api-token
      remoteRef:
        key: {{ .Values.cloudflareToken.externalSecret.remoteRef.key | quote }}
        property: {{ .Values.cloudflareToken.externalSecret.remoteRef.property | quote }}
