{{- if and .Values.namespace.create (include "common-apps.namespace" .) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "common-apps.namespace" . }}
  labels:
    {{- include "common-apps.labels" . | nindent 4 }}
    {{- with .Values.namespace.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.namespace.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
