{{- range .Values.vaultStaticSecrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ required "vaultStaticSecrets entries require name" .name }}
  namespace: {{ default (include "app.namespace" $) .namespace }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- required "vaultStaticSecrets entries require spec" .spec | toYaml | nindent 2 }}
{{- end }}
